import Link from "next/link";
import type React from "react";
import { ArrowLeft, Bell, CalendarDays, FileText, Hotel, Image, LayoutDashboard, Menu, Settings, Sparkles, Users } from "lucide-react";
import { signOut } from "@/app/admin/actions";

const navigation = [
  ["Dashboard", "/admin", LayoutDashboard], ["Announcements", "/admin/announcements", Bell], ["Important dates", "/admin/dates", CalendarDays], ["Speakers", "/admin/speakers", Users], ["Committees", "/admin/committees", Users], ["Registration", "/admin/registration", FileText], ["Programme", "/admin/programme", CalendarDays], ["Documents", "/admin/documents", FileText], ["Accommodation", "/admin/accommodation", Hotel], ["Publications", "/admin/publications", Sparkles], ["Sponsors", "/admin/sponsors", Sparkles], ["Gallery", "/admin/gallery", Image], ["FAQs", "/admin/faqs", FileText], ["Site settings", "/admin/settings", Settings],
] as const;

export function AdminShell({ children, email }: { children: React.ReactNode; email: string }) {
  return <div data-admin className="min-h-screen bg-[#f6f8f6] font-body text-dark-text"><aside className="fixed inset-y-0 hidden w-64 overflow-y-auto bg-primary-dark px-5 py-7 text-light-text lg:block"><Link href="/admin" className="flex items-baseline"><span className="font-display text-2xl">RECYCLE</span><span className="font-display text-2xl text-primary-emerald">27</span><span className="ml-2 text-[10px] uppercase tracking-[.18em] text-muted-green">Admin</span></Link><nav className="mt-10 space-y-1">{navigation.map(([label, href, Icon]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-light-text/70 transition hover:bg-white/10 hover:text-light-text"><Icon size={17} />{label}</Link>)}</nav><div className="mt-10 border-t border-dark-border pt-6"><p className="truncate px-3 text-xs text-light-text/50">{email}</p><form action={signOut}><button className="mt-3 flex items-center gap-2 px-3 text-sm text-muted-green"><ArrowLeft size={16} />Sign out</button></form><Link href="/" className="mt-5 flex items-center gap-2 px-3 text-sm text-light-text/70"><ArrowLeft size={16} />Back to website</Link></div></aside><main className="min-h-screen lg:pl-64"><header className="flex h-18 items-center justify-between border-b border-light-border bg-white px-5 md:px-9"><span className="flex items-center gap-2 text-sm font-medium"><Menu className="lg:hidden" size={18}/> Content manager</span><span className="hidden text-xs text-secondary-text sm:block">RECYCLE27 administration</span></header><div className="p-5 md:p-9">{children}</div></main></div>;
}
