"use client";
import { Search, Plus, Pencil, Trash2 } from "lucide-react";
import { useState } from "react";

type Props = { title: string; description: string; columns: string[]; rows: string[][] };
export function AdminCollection({ title, description, columns, rows }: Props) {
  const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false);
  const filtered = rows.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase()));
  return <><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-primary-emerald">Content</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-secondary-text">{description}</p></div><button onClick={() => setShowForm(!showForm)} className="inline-flex items-center gap-2 rounded-lg bg-primary-emerald px-4 py-2.5 text-sm font-medium text-white hover:bg-deep-emerald"><Plus size={17}/>{showForm ? "Close form" : `Add ${title.slice(0, -1)}`}</button></div>
  {showForm && <form className="mt-7 grid gap-4 border border-light-border bg-white p-6 md:grid-cols-2"><label className="md:col-span-2">Title / name<input required placeholder={`New ${title.slice(0, -1).toLowerCase()}`} /></label><label>Status<select defaultValue="active"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Sort order<input type="number" defaultValue="0" min="0" /></label><label className="md:col-span-2">Description<textarea rows={4} placeholder="Add the content details…" /></label><p className="md:col-span-2 text-xs text-secondary-text">Connect this form to the Supabase table after the project schema is applied.</p><button type="button" className="w-fit rounded-lg bg-primary-dark px-4 py-2.5 text-sm font-medium text-white">Save draft</button></form>}
  <div className="mt-8 overflow-hidden border border-light-border bg-white"><div className="border-b border-light-border p-4"><label className="relative block max-w-sm"><Search className="absolute left-3 top-3 text-secondary-text" size={16}/><input aria-label={`Search ${title.toLowerCase()}`} value={query} onChange={(event) => setQuery(event.target.value)} className="w-full pl-9" placeholder={`Search ${title.toLowerCase()}...`} /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-soft-bg text-xs uppercase tracking-[.08em] text-secondary-text"><tr>{columns.map((column) => <th key={column} className="px-5 py-3 font-medium">{column}</th>)}<th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-light-border">{filtered.length ? filtered.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`} className="px-5 py-4 text-secondary-text">{cellIndex === row.length - 1 && (cell === "Active" || cell === "Draft") ? <span className={`rounded-full px-2 py-1 text-xs ${cell === "Active" ? "bg-primary-emerald/10 text-deep-emerald" : "bg-soft-bg text-secondary-text"}`}>{cell}</span> : cell}</td>)}<td className="px-5 py-4"><div className="flex gap-3 text-secondary-text"><button aria-label="Edit item"><Pencil size={16}/></button><button aria-label="Delete item"><Trash2 size={16}/></button></div></td></tr>) : <tr><td colSpan={columns.length + 1} className="px-5 py-10 text-center text-secondary-text">No matching content.</td></tr>}</tbody></table></div></div></>;
}
